name: Django Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Python/Django Setup ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      # --- Run Django Tests ---
      - name: Run Django Tests
        run: |
          cd backend
          python manage.py test --noinput